import subprocess

revision = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode().strip()
with open("./src/loom/_revision.py", "w") as f:
    f.write(f'"""Records Loom source revision as seen by the distribution system.\n')
    f.write(f'(AUTOGENERATED by ./scripts/update-revision.py) """\n\n')
    f.write(f'__revision__ = "{revision}"\n')
